baseURL: "https://antonialoytorrens.com/"
languageCode: "en-us"
title: "antonialoytorrens.com"
#googleAnalytics: "UA-12341234-1"
#disqusShortname: "https-hostname-com"
defaultContentLanguage: "en"
pygmentsUseClasses: true
enableRobotsTXT: true

author:
  name: "Antoni Aloy Torrens"

params:
  since: 2018
  avatar: "/images/cyberpunk-ai.png"
  errorPage: "/images/gopher-this-is-fine.jpg"

languages:
  en:
    languageName: "English"
    weight: 1
    menu:
      main:
      - name: "Home"
        url: "/"
        weight: -150
      - name: "Blog"
        url: "/blog/"
        weight: -140
      - name: "Code"
        url: "/code/"
        weight: -130
      - name: "About"
        url: "/about/"
        weight: -110
  es:
    languageName: "Spanish"
    weight: 2
    menu:
      main:
      - name: "Inicio"
        url: "/"
        weight: -150
      - name: "Blog"
        url: "/blog/"
        weight: -140
      - name: "Código"
        url: "/code/"
        weight: -130
      - name: "Quién"
        url: "/about/"
        weight: -110
  ca:
    languageName: "Catalan"
    weight: 3
    menu:
      main:
      - name: "Inici"
        url: "/"
        weight: -150
      - name: "Bloc"
        url: "/blog/"
        weight: -140
      - name: "Codi"
        url: "/code/"
        weight: -130
      - name: "Qui"
        url: "/about/"
        weight: -110