baseURL: https://antonialoytorrens.com
languageCode: en
title: Antoni Aloy Torrens

# Default content language, support en (English) / zh (Chinese) / nl (Dutch) / fr (French) / es (Spanish) / da (Danish), default 'en'
defaultContentLanguage: en
defaultContentLanguageInSubdir: true
hasCJKLanguage: true
permalinks:
  posts: /blog/:year/:month/:slug/

paginate: 3

# See https://stackoverflow.com/a/59760977
frontmatter:
  date: 
    - publishDate
    - :filename
    - date
    - :fileModTime
  publishDate: 
    - publishDate
    - :filename
    - date
    - :fileModTime

# Hugo configure languages
languages:
  en:
    contentDir: "content_raw/en"
    languageCode: "en-US"
    languageDirection: "ltr"
    languageName: "EN"
    menu:
      main:
        - name: "Blog"
          url: "/en/blog/"
          weight: -130
        - name: "Education"
          url: "/en/education/"
          weight: -120
        - name: "Experience"
          url: "/en/experience/"
          weight: -110
        - name: "Projects"
          url: "/en/projects/"
          weight: -100
        - name: "RSS"
          url: "/en/blog/index.xml"
          weight: -90
    weight: 1
  es:
    contentDir: "content_raw/es"
    languageCode: "es-ES"
    languageDirection: "ltr"
    languageName: "ES"
    menu:
      main:
        - name: "Blog"
          url: "/es/blog/"
          weight: -130
        - name: "Educación"
          url: "/es/education/"
          weight: -120
        - name: "Experiencia"
          url: "/es/experience/"
          weight: -110
        - name: "Proyectos"
          url: "/es/projects/"
          weight: -100
        - name: "RSS"
          url: "/es/blog/index.xml"
          weight: -90
    weight: 2
  ca:
    contentDir: "content_raw/ca"
    languageCode: "es-CA"
    languageDirection: "ltr"
    languageName: "CA"
    menu:
      main:
        - name: "Blog"
          url: "/ca/blog/"
          weight: -130
        - name: "Educació"
          url: "/ca/education/"
          weight: -120
        - name: "Experiència"
          url: "/ca/experience/"
          weight: -110
        - name: "Projectes"
          url: "/ca/projects/"
          weight: -100
        - name: "RSS"
          url: "/ca/blog/index.xml"
          weight: -90
    weight: 3


# Hugo Configure Markup
# More info: https://gohugo.io/getting-started/configuration-markup#
markup:
  highlight:
    guessSyntax: true
    style: emacs
  tableOfContents:
    endLevel: 3
    ordered: false
    startLevel: 2
  # needed to render raw HTML (e.g. <sub>, <sup>, <kbd>, <mark>)
  goldmark:
    renderer:
      unsafe: true

# Social links in footer, support github,twitter,stackoverflow,facebook
social:
  linkedin: https://www.linkedin.com/in/antoni-aloy-torrens-7283481b2/
  github: https://github.com/antonialoytorrens
  #gitlab: https://gitlab.com/antonialoytorrens
  #xda: https://forum.xda-developers.com/member.php?u=10788301
  # twitter: your-github-link
  # stackoverflow: your-github-link
  # facebook: your-facebook-link

# Privacy
instagram:
  disable: false
  simple: true

twitter:
  disable: false
  enableDNT: true
  simple: true

vimeo:
  disable: false
  enableDNT: true
  simple: true

youtube:
  disable: false
  privacyEnhanced: true

# Site parameters
# Retrievable with (.Site.Params.paramName), where paramName is any variable inside params from below.
params:
  # Site Author
  author: Antoni Aloy Torrens
  # Site Description, used in HTML meat
  description: Blog and Portfolio of Antoni Aloy Torrens


  ###########################################
  # Optional Configuration
  ###########################################

  # To enable RSS, you could set `enableRSS: true`, default is `true`
  enableRSS: true
  # To enable comments, you may need to set `disqusShortname`
  # enableComments: true
  # To enable comments, you may need to set `googleAnalytics`
  # enableGoogleAnalytics: true
  # To enable table of content, you could set `showToc: true`, default is `false`
  showToc: false
  # To hidden powerBy message in the page footer, you could set: `showPowerBy: false`, default is `true`
  showPowerBy: true
  # To enable math typesetting , you could set `math: true`, default is `false`
  math: false
  # To hidden post summary in home page, you could set `hiddenPostSummaryInHomePage: true`, default is `false`
  hiddenPostSummaryInHomePage: false
  # Website copy write, default: '© Copyright 2023 ❤️ {params.author}'
  copyright: '' 

  # You can put your custom css and js to `static` directory, or use remote css and js files which start with `http://` or `https://`
  customCSS:
    ## e.g.
    # - css/custom.css # local css in `static/css/custom.css`
    # - https://example.com/custom.css # remote css
  customJS:
    ## e.g.
    # - js/custom.js # local js in `static/js/custom.js`
    # - https://example.com/custom.js # remote js