sonar.projectKey=portfolio
sonar.projectName=portfolio
sonar.sourceEncoding=UTF-8
sonar.sources=main,portfolio,manage.py
sonar.exclusions=**/media/**,**/static/**,**/public/**,**/db.sqlite3
sonar.python.coverage.reportPaths=coverage.xml,reports/coverage.xml
