# Generated by Django 3.0.7 on 2020-09-10 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200910_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='alt',
            field=models.CharField(default='-', max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='longdesc',
            field=models.CharField(default='-', max_length=2000),
            preserve_default=False,
        ),
    ]
