# Generated by Django 3.0.7 on 2020-09-15 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200910_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='alt_ca',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='alt_en',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='alt_es',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='longdesc_ca',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='longdesc_en',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='longdesc_es',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='subtitle_ca',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='subtitle_en',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='subtitle_es',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='title_ca',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='title_en',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='title_es',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='web_name_ca',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='web_name_en',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='web_name_es',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
